title: COVID-19s progression in Portugal
subtitle:
date: March 2020
author:
  - name: Pedro Ribeiro
    number: A85493
    avatar: pedro.jpg
keywords: [layers]
lang: en-EN
toc: true
numbersections: false
geometry: margin=2.5cm
